################################### English language #####################################
[en]
title = "An Innovative Operating System for Alternative Schools"
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# copyright
copyright = "(C) 2022 SELFSCRUM. All Rights Reserved. Icons by [icons8](https://icons8.com)"



################################### German language #####################################
[de]
title = "Ein Lern-, Organisations- und Betriebssystem für alternative Schulen"
languageName = "De"
languageCode = "de-de"
contentDir = "content/deutsch"
weight = 1
# copyright
copyright = "(C) 2022 SELFSCRUM. Alle Rechte vorbehalten. Icons von [icons8](https://icons8.com)"