############# German navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Lernende"
url = "how-it-works/"
weight = 5

[[main]]
name = "Schulen"
url = "case-studies/"
weight = 6

[[main]]
name = "Blog"
url = "blog/"
weight = 7

[[main]]
weight = 9
name = "Infos"
hasChildren = true

  [[main]]
  name = "Über uns"
  parent = "Infos"
  url = "about/"
  weight = 1

  [[main]]
  name = "Arbeite mit uns"
  parent = "Infos"
  url = "career/"
  weight = 2

  [[main]]
  parent = "Infos"
  name = "Impressum/Datenschutz"
  url = "/privacy"
  weight = 8
  
  [[main]]
  parent = "Infos"
  name = "RSS Feed"
  url = "/index.xml"
  weight = 9

[[main]]
name = "Kontakt"
url = "contact/"
weight = 15


# footer menu
[[footer]]
name = "Für Lernende"
url = "how-it-works/"
weight = 1

[[footer]]
name = "Für Schulen"
url = "case-studies/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3

