############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Learners"
url = "en/how-it-works"
weight = 5

[[main]]
name = "Blog"
url = "blog/"
weight = 7

[[main]]
weight = 9
name = "Infos"
hasChildren = true

  [[main]]
  parent = "Infos"
  name = "About us"
  url = "about/"
  weight = 1

  [[main]]
  parent = "Infos"
  name = "Imprint/Privacy"
  url = "privacy/"
  weight = 8

  [[main]]
  parent = "Infos"
  name = "RSS Feed"
  url = "/en/index.xml"
  weight = 9

[[main]]
name = "Contact"
url = "contact/"
weight = 15


# footer menu
[[footer]]
name = "About Us"
url = "about/"
weight = 1

[[footer]]
name = "For Learners"
url = "how-it-works/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3
